### PR TITLE
Simplify

### PR DESCRIPTION
**Pull request by krlmlr**
for CRAN release.

### CODE REVIEW

**Comment by krlmlr** [comment]
@maelle: Can you please help make this CRAN-ready? In terms of examples, we could create a dummy class and dummy methods that print something, directly in the examples. I'll adapt the documentation text.

**Comment by maelle** [comment]
@krlmlr when you write

> I'll adapt the documentation text.

Will the docs refer to the full-featured version of the package, and explain how to install it?

**Comment by maelle** [comment]
@krlmlr I opened #35 with easy fixes. For other errors, I need a bit more context. I get errors for missing functions, so am adding back pieces in a seemingly never ending process, so maybe instead I should tweak the existing examples? How did you choose what to include here?

**Comment by maelle** [comment]
@krlmlr what exactly do you mean by dummy class? I added [`b17e9bb` (#35)](https://github.com/duckdblabs/duckplyr/pull/35/commits/b17e9bb2dcb297bcafb48f6d1510fbf9264129f2)

**Comment by krlmlr** [comment]
Thanks. I'll take another stab and will get back to you.

**Comment by krlmlr** [comment]
On CRAN now.

**Pull request closed without merging**
