### PR TITLE
Update scripts to run out of the box

### PR DESCRIPTION
**Pull request by Tmonster**
Now that duckdb 0.8.0 has been released. Many of the benchmarking and comparison scripts can be updated to run out of the box (once all dependencies are installed). 

This PR increases the tolerance for the compare scripts since the parallel scans of data frames results in a small loss of precision. I imagine 4e-12 is still acceptable. 

Many of the scripts change the name of the queries from `tpch_XX` to `qXX`. This is so that when the queries are graphed, we don't display `tpch_XX` for every query. It's just a small change.

Added a `load-compare-bench.R` script so that the user can execute one command to see the results.

### CODE REVIEW

**Comment by Tmonster** [comment]
@krlmlr Yea, I was planning on reverting the "tpch_01" -> "q01" names for the scripts. Also want to change the raw relational scripts. I'll do that now

**Comment by krlmlr** [comment]
Thanks. We can revert 9f61193 if needed. I'll do some measuring myself and then merge.

**Comment by krlmlr** [comment]
I misread. I'm not surprised that running raw relational queries is faster than running SQL. How much faster is it?

I'm much more surprised that query 1 has a huge overhead in duckplyr. Will review.

**Comment by krlmlr** [comment]
Got you. We need `nrow()` for the `tpch_raw_xx()` functions instead of `collect()` to materialize.

**Comment by krlmlr** [comment]
Weird. Now the raw queries take longer than running through duckplyr. Will investigate.

**Comment by krlmlr** [comment]
Even with the `gc()` the timings are all over the place.

With sf = 0.1 and 10 repetitions, I achieved consistently faster times for "raw" than for "duckplyr". Perhaps a JIT thing? We may want to take multiple samples here too.

**Comment by krlmlr** [comment]
Not a JIT thing, giving up.

Will adapt the plotting script and finally merge.

**Comment by krlmlr** [comment]
Thanks!

**Pull request merged**
